server:
  port: 5555

spring:
  application:
    name: springcloud-zull

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    instance:
      instancd-id: zuul5555.com
      prefer-ip-address: true
info:
  app.name: soil-springcloud
  company.name: blog.soilstudy.com

zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept
    mydept.path: /mydept/**
#  ignored-services: springcloud-provider-dept #不能使用该路径访问
  ignored-services: "*" #隐藏全部项目路径
  prefix: /soil  #公共的访问前缀